### DISCUSSION TITLE
FFPyPlayer does not play sound

### DISCUSSION THREAD

**Discussion by ok-coder1** [kivy/kivy-github-discussions#32] [Q&A] [answered]
I have created a file that plays sound through Kivy's SoundLoader.

alarm.py
```
from kivy.app import App
from kivy.uix.widget import Widget
#from kivy.core.audio import SoundLoader

class AppLayout(Widget):
    '''def set_time(self, time):
        self.ids.time_picker.set_time(time)'''

class Alarm(App):
    def build(self):
        return AppLayout()

if __name__ == "__main__":
    Alarm().run()
```

alarm.kv
```
#:import CircularTimePicker circulardatetimepicker
#:import Factory kivy.factory.Factory
#:import SoundLoader kivy.core.audio.SoundLoader

<TimeSelect@Popup>
    title: "Select Time"
    size_hint: 0.8, 0.6

    BoxLayout:

        CircularTimePicker:
            id: time_picker

        Button:
            text: "Close"
            font_size: 16
            on_release: root.dismiss()

<AppLayout>

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            text: "Alarm Clock"

        Button:
            text: "Select Time"
            font_size: 16
            on_release: Factory.TimeSelect().open()

        Label:
            text: "UNDER CONSTRUCTION"

        Button:
            id: alarm_test
            text: "Test Alarm Sound"
            font_size: 16
            on_release: SoundLoader.load("alarm-clock-ringing-fascinatedsound-1-00-03.mp3")
```

`alarm-clock-ringing-fascinatedsound-1-00-03.mp3` is in the same directory as these two files.

Also if I spam the `Test Alarm Sound` button, this is the error I get,
```
[WARNING] [ffpyplayer  ] SDL_OpenAudio (2 channels, 44100 Hz): Too many open audio devices
[WARNING] [ffpyplayer  ] SDL_OpenAudio (1 channels, 44100 Hz): Too many open audio devices
[ERROR  ] [ffpyplayer  ] No more channel combinations to try, audio open failed
[CRITICAL] [ffpyplayer  ] Failed to open file '/Users/User/Desktop/tkdesigner-figma/alarm-clock/alarm-clock-ringing-fascinatedsound-1-00-03.mp3' or configure filtergraph
```
