### DISCUSSION TITLE
Unable to run GraphicalUnitTest in github-action runners: `macos-*`

### DISCUSSION THREAD

**Discussion by qlrd** [kivy/kivy-github-discussions#34] [Q&A]
#### Summary of situation

I'm developing kivy app to run in 3 major OS (linux, windows, mac) and currently writing simple  unit tests with the `GraphicalUnitTest` class in a github-action:

```python
class TestBaseScreen(GraphicUnitTest):

    @patch.object(EventLoopBase, "ensure_window", lambda x: None)
    def test_render(self):
        screen = BaseScreen(wid="mock", name="Mock")
        self.render(screen)

        # get your Window instance safely
        EventLoop.ensure_window()
        window = EventLoop.window

        # your asserts
        self.assertEqual(window.children[0], screen)
        self.assertEqual(window.children[0].height, window.height)
```

Where `BaseScreen` is a subclass of `Screen` (see source [here](https://github.com/qlrd/krux-installer/blob/kivy/src/app/base_screen.py)).

*EDIT*

The test setup in github is:

```yaml
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
      
      - name: Install project and its dependencies
        run: poetry install
      
      - name: Run tests (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            poetry add pytest-xvfb
            poetry run poe test

      - name: Run tests (Windows)
        if: ${{ runner.os == 'Windows' }}
        env:
          KIVY_GL_BACKEND: 'angle_sdl2'
        run: poetry run poe test
      
      - name: Run tests (macOS)
        if: ${{ runner.os == 'macOS' }}
        env:
          USE_SDL2: 1
          KIVY_GL_BACKEND: 'sdl2'
        run: poetry run poe test
```

This works well in Linux machine since an Xvfb and [pytest-xvfb plugin](https://pypi.org/project/pytest-xvfb/) was used for this purpose. This is working well in Windows using `KIVY_GL_BACKEND=angle_sdl2`. All environment variables are from [Kivy workflows](https://github.com/kivy/kivy/tree/master/.github/workflows).

However,`macos` runners do not occur properly. The `pytest` start to be executed and when the graphics tests are started, an error is reported:

```bash
_________________________ TestBaseScreen.test_on_press _________________________

self = <tests.test_030_base_screen.TestBaseScreen testMethod=test_on_press>

    def setUp(self):
        '''Prepare the graphic test, with:
            - Window size fixed to 320x240
            - Default kivy configuration
            - Without any kivy input
        '''
    
        # use default kivy configuration (don't load user file.)
        from os import environ
        environ['KIVY_USE_DEFAULTCONFIG'] = '1'
    
        # force window size + remove all inputs
        from kivy.config import Config
        Config.set('graphics', 'width', '320')
        Config.set('graphics', 'height', '240')
        for items in Config.items('input'):
            Config.remove_option('input', items[0])
    
        # bind ourself for the later screenshot
        from kivy.core.window import Window
        self.Window = Window
>       Window.bind(on_flip=self.on_window_flip)
E       AttributeError: 'NoneType' object has no attribute 'bind'
```

I believe that such errors happen because runners do not have a graphical interface. But i don´t know how to fix it. It is in this sense that I come to SO for help, that is, run the graphical tests on MacOS, despite the lack of a window manager, in the same way as was done on the Linux/Windows runners.

Thanks in advance
