### DISCUSSION TITLE
Confused about root object and class object and their referencing

### DISCUSSION THREAD

**Discussion by suhsin85** [kivy/kivy-github-discussions#41] [Q&A]
Here are the py and kv codes for a simple app that's aimed at helping me understand referencing objects using kivy properties. My questions are:
1. Is CustomLayout effectively the root object, since its first button calls for root.move_slider() when pressed?
2. Can I swap the order of CustomLayout and TestLayout around so that TestLayout becomes the root object because it is on top of the hierarchy and have the app still work the same?
3. When trying to reference kivy ids within the python file, how do I know when to reference using "self.ids.___" vs "self.parent.ids.___"? 
4. I thought root objects aren't enclosed in angle brackets, why is CustomLayout being done so?

py code:
```
...  
class TestLayout(FloatLayout):
    pass  
class CustomLayout(BoxLayout):  
    def move_slider(self):  
        if self.ids._slider.value <= self.ids._slider.max - 5:  
            self.ids._slider.value += 5  
class CustomButton(Button):  
    def set_text(self):  
        self.parent.ids._label2.text = 'CHANGED'  
class TestApp(App):  
    def build(self):  return TestLayout()  
if  __name__  ==  '__main__':  TestApp().run() 
```

kv code:
```
<CustomLayout>:  
    size_hint: .5, .5  
    pos_hint: {'x': .5, 'top': 1}  
    Button:  
        text: str(_slider.orientation)  
        on_press: root.move_slider()  
    BoxLayout:  
        orientation: 'vertical'  
        Button:  text: str(_slider.orientation)  
        Slider:  
            id:  _slider  
            min: 100  
            max: 200  
            value: 150  
            `orientation:` 'vertical'
        Button:  
            text: str(_slider.value)  
    Button:  text: str(_slider.orientation)  
<TestLayout>:  
    Label:  
        text:  _label2.text  
        size_hint: .5, .5  
        pos_hint: {'x': 0, 'top': 1}  
    CustomLayout:  
    CustomButton:  
        id:  _customButton  
        text:  _label2.text  
        size_hint: .5, .5  
        pos_hint: {'x': 0, 'y': 0}  
        on_press: self.set_text()  
    Label:  
        id:  _label2  
        text: 'label 2'  
        size_hint: .5, .5  
        pos_hint: {'x': .5, 'y': 0}  
```
